schema_version = "1.0.0"

id = "uv_padding_overlay"
version = "1.5.2"
name = "UV Padding Overlay"
tagline = "Display padding outline around UV shells"
maintainer = "Artic"
type = "add-on"

tags = ["UV"]
blender_version_min = "4.2.0"
blender_version_max = "5.4.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
]
